Add debug prints to module_load

diff --git a/misc-modules/module_load b/misc-modules/module_load
--- a/misc-modules/module_load
+++ b/misc-modules/module_load
@@ -1,7 +1,9 @@
 #!/bin/sh
 module=$1
+echo "module = $module"
 # Use the same name for the device as the name used for the module
 device=$1
+echo "device = $device"
 # Support read/write for owner and group, read only for everyone using 644
 mode="664"
 
@@ -22,9 +24,17 @@ else
 fi
 
 echo "Load our module, exit on failure"
-modprobe $module $* || exit 1
+#modprobe $module $* || exit 1
+if modprobe $module $* ; then
+    echo "Module $module loaded successfully."
+else
+    echo "Failed to load module $module."
+    exit 1
+fi
+
 echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
+echo "major = $major"
 if [ ! -z ${major} ]; then
     echo "Remove any existing /dev node for /dev/${device}"
     rm -f /dev/${device}
